### ISSUE TITLE
What is this doing?

### ISSUE THREAD

**Issue by abhyuditjain** [Cryonis/Phasmophobia-Save-Manager#1]
I was going through the code and couldn't figure out why this was done:

```
StringBuilder text = new StringBuilder();
for (int i = 0; i < data.Length; i++)
{
    text.Append((char)(data[i] ^ Constants.SaveFilePassword[i % Constants.SaveFilePassword.Length]));  // this line
}
saveFileData = JObject.Parse(text.ToString());
```

The `Constants,SaveFilePassword` is a random string, then how do you decode it?

**Comment by Ceveos** [comment]
So the save file is a JSON file encrypted via XOR. XOR uses a constant password to encrypt/decrypt the file.
I had to reverse engineer the password off of Phasmophobia. The password was stored in Constants.SaveFilePassword.

so tl;dr - this is decrypting your save file.

**Comment by abhyuditjain** [comment]
How do I find the password? Also, how did you reverse engineer that?

**Comment by Ceveos** [comment]
Password is listed in the constants here: https://github.com/Cryonis/Phasmophobia-Save-Manager/blob/main/Configuration/Constants.cs

I won't go into how I reverse engineered the password out of respect for the game.

**Comment by abhyuditjain** [comment]
Oh I thought you wanted the user of the repository to change the password for his user ("CHANGE ME TO YOUR OWN RANDOM STRING"). So the game uses the same password for every user.

I understand. I was just wondering how to get started with reverse engineering (not particularly Phasmophobia).

**Comment by Ceveos** [comment]
Ghidra and ILSpy are the tools you might be interested in using. ILSpy is useful to decrypt C# programs / DLL's - and Unity uses Mono (which is C#).
